version: "3.3"

services:

  racedisplay-service:
    image: racedisplay-service
    build: ./streamlit
    depends_on:
      - driftapi-db
    environment:
      STREAMLIT_DRIFTAPI_PATH: ${STREAMLIT_DRIFTAPI_PATH}
      STREAMLIT_SERVER_PORT: ${STREAMLIT_SERVER_PORT}
    ports:
      - 8080:8080
    profiles:
      - racedisplay

  driftapi-service:
    image: driftapi-service
    build: ./driftapi
    depends_on:
      - driftapi-db
    environment:
      DRIFTAPI_DATABASE_URL:  ${DRIFTAPI_DATABASE_URL}
      DRIFTAPI_DATABASE_NAME: ${DRIFTAPI_DATABASE_NAME}
      DRIFTAPI_ROOT_PATH: ${DRIFTAPI_ROOT_PATH}
      DRIFTAPI_DISABLE_OPENAPI: ${DRIFTAPI_DISABLE_OPENAPI}
      DRIFTAPI_CORS_ALLOW_ORIGINS: ${DRIFTAPI_CORS_ALLOW_ORIGINS}
    ports:
      - 8001:8001

  driftapi-db:
    image: mongo
    ports:
      - 27018:27017

